// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjfnfmkpqzqnmxgytunn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZm5mbWtwcXpxbm14Z3l0dW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNzAxNTcsImV4cCI6MjA1Mzk0NjE1N30.dQVas4tQC7gaVnunNCbZdc3H7fj-3VW4UYRh9Ti-sSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);